--!strict

local Constants = {
	Remotes = {
		Folder = "Remotes",
		Request = "BrawlRequest",
		State = "BrawlState",
		Events = "BrawlEvents",
		Arena = "BrawlArenaState",
	},
	Actions = {
		Punch = "Punch",
		HeavyPunch = "HeavyPunch",
		DodgeRoll = "DodgeRoll",
	},
	EventTypes = {
		KillFeed = "KillFeed",
		Streak = "Streak",
		LevelUp = "LevelUp",
		RankUp = "RankUp",
		SeriesEvent = "SeriesEvent",
		XPGain = "XPGain",
	},
	Combat = {
		PunchRange = 5,
		PunchBoxBackOffset = 2,
		PunchBoxHeight = 6,
		PunchBoxDepth = 2.5,
		PunchCloseRadius = 3.5,
		PunchDamage = 10,
		PunchCooldown = 0.4,
		PunchStartupLockSeconds = 0.15,
		PunchHitDelaySeconds = 0.18,
		HeavyPunchRange = 8,
		HeavyPunchCooldown = 1.2,
		HeavyPunchMultiplier = 3,
		HeavyPunchStartupLockSeconds = 0.4,
		HeavyPunchHitDelaySeconds = 0.6,
		HitStopTargetLight = 0.08,
		HitStopTargetHeavy = 0.14,
		HitStopPuncherLight = 0.04,
		HitStopPuncherHeavy = 0.07,
		InputBufferWindow = 0.15,
		DodgeRollCooldown = 3.0,
		DodgeRollDurationSeconds = 0.5,
		DodgeRollVelocityMultiplier = 1.5,
		DodgeRollAnimSpeedMultiplier = 2.0,
		DoubleJumpVelocity = 75,
		KnockbackBase = 40,
		KnockbackGrowth = 1.5,
		KnockbackVertical = 35,
		RateLimitWindow = 1.0,
		RateLimitMaxRequests = 4,
	},
	Arena = {
		YKillThreshold = -50,
		AxisLockValue = 0,
		KillAttributionWindow = 5.0,
		InvincibilityDuration = 1.0,
	},
	PlayerState = {
		InLobby = "InLobby",
		InArena = "InArena",
	},
	PlayerMovement = {
		WalkSpeed = 32,
		JumpHeight = 14.4,
		JumpPower = 100,
	},
	CollisionGroups = {
		Players = "BrawlPlayers",
		PlayersDodging = "BrawlPlayersDodging",
	},
	Tags = {
		JumpThroughPlatform = "BrawlJumpThrough",
		DonateKiosk = "BrawlDonateKiosk",
		FadingLabel = "BrawlFadingLabel",
	},
	CharacterAttributes = {
		HitSeq = "BrawlHitSeq",
		EliminationSeq = "BrawlEliminationSeq",
		LastHitterId = "BrawlLastHitterId",
		LastHitTime = "BrawlLastHitTime",
		InvincibleUntil = "BrawlInvincibleUntil",
		DamagePercent = "BrawlDamagePercent",
		KBVelocity = "BrawlKBVelocity",
		KBSeq = "BrawlKBSeq",
		ArenaActive = "BrawlArenaActive",
		HitKind = "BrawlHitKind",
		HitStopUntil = "BrawlHitStopUntil",
		HitStopSeq = "BrawlHitStopSeq",
		Level = "BrawlLevel",
		RankName = "BrawlRankName",
		RankTier = "BrawlRankTier",
	},
	XP = {
		Base = 20,
		TierBonusPercent = 0.30,
		LevelCurveMultiplier = 80,
		LevelCurveExponent = 1.4,
		LevelCurveExponentGrowth = 0.001,
	},
	Rank = {
		Tiers = {
			{ name = "Unranked",     threshold = 0 },
			{ name = "Bronze I",     threshold = 100 },
			{ name = "Bronze II",    threshold = 200 },
			{ name = "Bronze III",   threshold = 300 },
			{ name = "Silver I",     threshold = 400 },
			{ name = "Silver II",    threshold = 500 },
			{ name = "Silver III",   threshold = 600 },
			{ name = "Gold I",       threshold = 700 },
			{ name = "Gold II",      threshold = 800 },
			{ name = "Gold III",     threshold = 900 },
			{ name = "Platinum I",   threshold = 1000 },
			{ name = "Platinum II",  threshold = 1100 },
			{ name = "Platinum III", threshold = 1200 },
			{ name = "Diamond I",    threshold = 1300 },
			{ name = "Diamond II",   threshold = 1400 },
			{ name = "Diamond III",  threshold = 1500 },
			{ name = "Champion",     threshold = 1600 },
		},
		PointsPerTier = 100,
		DivisionRates = {
			Unranked = { kill = 20, death = 0 },
			Bronze   = { kill = 15, death = 1 },
			Silver   = { kill = 10, death = 3 },
			Gold     = { kill = 10, death = 5 },
			Platinum = { kill = 6,  death = 4 },
			Diamond  = { kill = 4,  death = 3 },
			Champion = { kill = 1,  death = 1 },
		},
		SeriesLength = 3,
		PromoFailLanding = 75,
		DemoteFailLanding = 25,
		DemoteSuccessLanding = 75,
	},
	Streak = {
		DoubleWindow = 5.0,
		TripleWindow = 8.0,
		DominatingThreshold = 5,
	},
	Donate = {
		ProductId = 3579571980,
		DisplayPrice = 100,
		ProductName = "Support the Dev",
	},
	FadingLabel = {
		NearDistance = 20,
		FarDistance = 80,
	},
	Analytics = {
		Events = {
			SessionStart = "session_start",
			SessionEnd = "session_end",
			Kill = "kill",
			LevelUp = "level_up",
			RankUp = "rank_up",
			Donate = "donate",
			EnterArena = "enter_arena",
			ReturnToLobby = "return_to_lobby",
		},
	},
	Assets = {
		PunchAnimationId = "rbxassetid://105919524623967",
		HeavyPunchAnimationId = "rbxassetid://83755342484641",
		RunAnimationId = "rbxassetid://105129044821151",
		DoubleJumpAnimationId = "rbxassetid://74399426620925",
		DodgeRollAnimationId = "rbxassetid://115857807557239",
		PunchHitSound = {
			Id = "rbxassetid://139697578472716",
			Volume = 0.7,
			RollOffMinDistance = 10,
			RollOffMaxDistance = 80,
		},
		EliminationSound = {
			Id = "rbxassetid://76627054450785",
			Volume = 0.85,
		},
	},
	DataStore = {
		ProfileStoreName = "BrawlArenaProfiles_v1",
		PurchaseDataStoreName = "BrawlArenaPurchases_v1",
		RankingStorePrefix = "BrawlArenaRanking_v2_",
	},
	Ranking = {
		Modes = {
			Level = "Level",
			Kills = "Kills",
			MMR = "MMR",
		},
		ModeDisplay = {
			Level = { title = "TOP LEVEL", scoreSuffix = "", accent = Color3.fromRGB(80, 180, 255) },
			Kills = { title = "TOP KILLS", scoreSuffix = "", accent = Color3.fromRGB(255, 100, 100) },
			MMR = { title = "TOP RANKING", scoreSuffix = "", accent = Color3.fromRGB(200, 120, 255) },
		},
		TopN = 10,
		RefreshIntervalSeconds = 20,
		MinScoreToSubmit = 1,
	},
}

return Constants
