--!strict

local Constants = {
	Remotes = {
		Folder = "Remotes",
		Request = "BrawlRequest",
		State = "BrawlState",
		Events = "BrawlEvents",
	},
	Actions = {
		Punch = "Punch",
		HeavyPunch = "HeavyPunch",
		DodgeRoll = "DodgeRoll",
	},
	EventTypes = {
		KillFeed = "KillFeed",
		Streak = "Streak",
		LevelUp = "LevelUp",
		RankUp = "RankUp",
		XPGain = "XPGain",
	},
	Combat = {
		PunchRange = 5,
		PunchBoxBackOffset = 2,
		PunchBoxHeight = 6,
		PunchBoxDepth = 2.5,
		PunchDamage = 10,
		PunchCooldown = 0.4,
		PunchStartupLockSeconds = 0.15,
		HeavyPunchCooldown = 1.2,
		HeavyPunchMultiplier = 3,
		HeavyPunchStartupLockSeconds = 0.4,
		DodgeRollCooldown = 2.0,
		DodgeRollDurationSeconds = 0.5,
		DodgeRollVelocityMultiplier = 1.5,
		DodgeRollAnimSpeedMultiplier = 2.0,
		DoubleJumpVelocity = 75,
		KnockbackBase = 40,
		KnockbackGrowth = 1.5,
		KnockbackVertical = 35,
		RateLimitWindow = 1.0,
		RateLimitMaxRequests = 4,
	},
	Arena = {
		YKillThreshold = -50,
		AxisLockValue = 0,
		KillAttributionWindow = 5.0,
		InvincibilityDuration = 1.0,
	},
	PlayerState = {
		InLobby = "InLobby",
		InArena = "InArena",
	},
	PlayerMovement = {
		WalkSpeed = 32,
		JumpHeight = 14.4,
		JumpPower = 100,
	},
	CollisionGroups = {
		Players = "BrawlPlayers",
		PlayersDodging = "BrawlPlayersDodging",
	},
	Tags = {
		JumpThroughPlatform = "BrawlJumpThrough",
		DonateKiosk = "BrawlDonateKiosk",
	},
	CharacterAttributes = {
		HitSeq = "BrawlHitSeq",
		EliminationSeq = "BrawlEliminationSeq",
		LastHitterId = "BrawlLastHitterId",
		LastHitTime = "BrawlLastHitTime",
		InvincibleUntil = "BrawlInvincibleUntil",
		DamagePercent = "BrawlDamagePercent",
		KBVelocity = "BrawlKBVelocity",
		KBSeq = "BrawlKBSeq",
		ArenaActive = "BrawlArenaActive",
	},
	XP = {
		Base = 20,
		MMRMultiplier = 10,
		BonusClampMin = -15,
		BonusClampMax = 100,
		ParticipationBonus = 5,
		PassiveDripPerSecond = 1,
		LevelCurveMultiplier = 100,
		LevelCurveExponent = 1.4,
	},
	Rank = {
		Tiers = {
			{ name = "Unranked",  threshold = 0 },
			{ name = "Bronze I",  threshold = 100 },
			{ name = "Bronze II", threshold = 250 },
			{ name = "Bronze III", threshold = 450 },
			{ name = "Silver I",  threshold = 700 },
			{ name = "Silver II", threshold = 1000 },
			{ name = "Silver III", threshold = 1350 },
			{ name = "Gold I",    threshold = 1750 },
			{ name = "Gold II",   threshold = 2200 },
			{ name = "Gold III",  threshold = 2700 },
			{ name = "Platinum I", threshold = 3250 },
			{ name = "Platinum II", threshold = 3850 },
			{ name = "Platinum III", threshold = 4500 },
			{ name = "Diamond",   threshold = 5300 },
			{ name = "Champion",  threshold = 7000 },
		},
		PointsPerKill = 15,
		PointsLostPerDeath = 5,
	},
	Streak = {
		DoubleWindow = 5.0,
		TripleWindow = 8.0,
		DominatingThreshold = 5,
	},
	Donate = {
		ProductId = 3579571980,
		DisplayPrice = 100,
		ProductName = "Support the Dev",
	},
	DonateKiosk = {
		FadeNearDistance = 20,
		FadeFarDistance = 80,
	},
	Analytics = {
		Events = {
			SessionStart = "session_start",
			SessionEnd = "session_end",
			Kill = "kill",
			LevelUp = "level_up",
			RankUp = "rank_up",
			Donate = "donate",
			EnterArena = "enter_arena",
			ReturnToLobby = "return_to_lobby",
		},
	},
	Assets = {
		PunchAnimationId = "rbxassetid://105919524623967",
		HeavyPunchAnimationId = "rbxassetid://83755342484641",
		RunAnimationId = "rbxassetid://105129044821151",
		DoubleJumpAnimationId = "rbxassetid://74399426620925",
		DodgeRollAnimationId = "rbxassetid://115857807557239",
		PunchHitSound = {
			Id = "rbxassetid://139697578472716",
			Volume = 0.7,
			RollOffMinDistance = 10,
			RollOffMaxDistance = 80,
		},
		EliminationSound = {
			Id = "rbxassetid://76627054450785",
			Volume = 0.85,
		},
	},
	DataStore = {
		ProfileStoreName = "BrawlArenaProfiles_v1",
		PurchaseDataStoreName = "BrawlArenaPurchases_v1",
		RankingStorePrefix = "BrawlArenaRanking_v1_",
	},
	Ranking = {
		Modes = {
			Level = "Level",
			Kills = "Kills",
			TimeAlive = "TimeAlive",
		},
		ModeDisplay = {
			Level = { title = "TOP LEVEL", scoreSuffix = "", accent = Color3.fromRGB(80, 180, 255) },
			Kills = { title = "TOP KILLS", scoreSuffix = " kills", accent = Color3.fromRGB(255, 100, 100) },
			TimeAlive = { title = "TOP SURVIVAL", scoreSuffix = "", accent = Color3.fromRGB(120, 220, 120) },
		},
		TopN = 10,
		RefreshIntervalSeconds = 60,
		MinScoreToSubmit = 1,
	},
}

return Constants
